/**
 * @file TestGLAD.cpp
 * @brief Basic test for GLAD OpenGL loader to validate integration.
 */

#include "doctest.h"

// Include GLAD headers - should compile without errors
// GLAD generates gl.h (not glad.h) in the glad/ subdirectory
#include <glad/gl.h>

TEST_SUITE("GLAD")
{
    TEST_CASE("GLAD headers compile and basic types are available")
    {
        // Verify that GLAD types are available
        // GLAD provides OpenGL function pointers and constants
        
        // Verify basic OpenGL constants are available (these come from the OpenGL spec)
        // These are compile-time constants defined in the OpenGL headers
        CHECK(GL_FALSE == 0);
        CHECK(GL_TRUE == 1);
        
        // Verify some common OpenGL constants are defined
        // These should be available regardless of OpenGL version
        CHECK(GL_POINTS >= 0);
        CHECK(GL_LINES >= 0);
        CHECK(GL_TRIANGLES >= 0);
        
        // Verify GLAD was generated for OpenGL 4.6 Core profile
        // The loader should support OpenGL 4.6 functions
        // We can't test actual function loading without an OpenGL context,
        // but we can verify the headers are correctly included
        
        // If we got here, the headers compiled successfully
        CHECK(true);
    }
    
    TEST_CASE("GLAD loader structure is available")
    {
        // GLAD provides a GLADloadfunc type for loading OpenGL functions
        // The actual loader function (gladLoadGL) requires an OpenGL context,
        // but we can verify the type definitions are available
        
        // Verify that GLAD defines the necessary types
        // These are generated by the GLAD generator based on the OpenGL spec
        // The fact that we can include the header and compile means the structure is available
        
        // If we got here, the loader structure is available
        CHECK(true);
    }
}